version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
      - '6379:6379'

  mongo:
    image: mongo:4
    ports:
      - '27017:27017'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
#      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: perfMon

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
